#ifndef INCLUDE_GUARD
#define INCLUDE_GUARD

#define PROJECT_NAME "CapeEEPROMViewer"
#define PROJECT_VER  "0.0.2"
#define PROJECT_VER_MAJOR "0"
#define PROJECT_VER_MINOR "0"
#define PTOJECT_VER_PATCH "2"

#endif // INCLUDE_GUARD
